routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
    Route::resource('/dashboard', 'DashboardController');
    Route::resource('/games', 'GamesController');
});

Route::namespace('Member')->prefix('member')->name('member.')->group(function(){
    Route::resource('/profile', 'ProfileController');
    Route::resource('/cart', 'CartController');
    Route::resource('/games', 'GameController');
    Route::resource('/notice', 'NoticeController');

    Route::get('cart/pdf-generate', 'PdfController@generatePDF')->name('cart.pdf');
    Route::get('cart/receipt', 'CartController@receipt')->name('cart.receipt');
    Route::get('profile/addMoney', 'ProfileController@addMoney')->name('profile.addMoney');

    Route::post('profile/updateMoney', 'ProfileController@updateMoney')->name('profile.updateMoney');
});

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    //
}

app/Http/Controllers/Member/CartController.php
<?php

namespace App\Http\Controllers\Member;

use App\Cart;
use App\Game;
use App\User;
use App\Http\Controllers\Controller;
use App\Mail\CheckUser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use niklasravnsborg\LaravelPdf\Facades\Pdf;

class CartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Game $game)
    {
        return view('member.cart.index')
            ->with('game', $game);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $double = Cart::search(function ($cartItem, $rowId) use ($request)
        {
            return $cartItem->id == $request->game_id;
        });

        if($double->isNoEmpty())
        {
            return redirect()->route('home')
                ->with('success', 'The Game has already been added');
        }

        $game = Game::find($request->game_id);

        Cart::add($game->id, $game->name, 1, $game->price)
            ->associate('App\Game');

        return redirect()->route('home')->with('success', 'The Game has been added in your Cart');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($rowId)
    {
        Cart::remove($rowId);

        return back()->with('success', 'The Game has been deleted successfully !');
    }
}

app/Http/Controllers/Member/GameController.php
<?php

namespace App\Http\Controllers\Member;

use App\Http\Controllers\Controller;
use App\Game;
use Illuminate\Http\Request;

class UserGameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Game $game)
    {
        return view('member.games.show')
            ->with(['game' => $game]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Member/NoticeController.php
<?php

namespace App\Http\Controllers\Member;

use App\Http\Controllers\Controller;
use App\Notice;
use App\Game;
use App\User;
use Illuminate\Http\Request;

class NoticeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request, Game $game)
    {
        $id_game = $request->input('id_game');
        return view('member.notice.create', [
            'id_game' => $id_game
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, User $user)
    {
        $note = $request->input('note');
        $description = $request->input('description');
        $game_id = $request->input('id_game');
        $author = $user = auth()->user()->name;

        $notice = new Notice;
        $notice->note = $note;
        $notice->description = $description;
        $notice->id_game = $game_id;
        $notice->author = $author;
        $notice->save();

        return redirect()->route('home');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Notice  $notice
     * @return \Illuminate\Http\Response
     */
    public function show(Notice $notice)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Notice  $notice
     * @return \Illuminate\Http\Response
     */
    public function edit(Notice $notice, Game $game, Request $request)
    {
        $id_game = $request->input('id_game');

        return view('member.notice.edit', ['id_game' => $id_game, 'notice' => $notice]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Notice  $notice
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Notice $notice)
    {
        $note = $request->input('note');
        $description = $request->input('description');

        $notice = Notice::find($notice->id);
        $notice->note = $note;
        $notice->description = $description;
        $notice->save();

        return redirect()->route('home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Notice  $notice
     * @return \Illuminate\Http\Response
     */
    public function destroy(Notice $notice, Game $game)
    {
        $notice->delete();

        return redirect()->route('home');
    }
}

app/Http/Controllers/Member/PdfController.php
<?php

namespace App\Http\Controllers\Member;

use App\Game;
use App\Cart;
use App\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Mail;
use PDF;

class PdfController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function generatePDF(Game $game, User $user)
    {
        $user = auth()->user();
        $currentUser = User::find(auth()->user()->id);

        $total = Cart::Subtotal();

        $moneys = $currentUser->moneys;

        if($moneys - $total >= 0)
        {
            $pdf = PDF::loadView('member/cart/receipt');
            $pdf->save('receipt.pdf');

            $data["email"] = $user->email;
            $data["title"] = "EgameCenter";

            $files = [
                public_path('receipt.pdf'),
            ];

            Mail::send('member/cart/receipt', $data, function ($message) use ($data, $files)
            {
                $message->to($data["email"], $data["email"])
                    ->subject($data["title"]);

                foreach($files as $file)
                {
                    $message->attach($file);
                }
            });

            $newMoneys = $moneys - $total;
            $currentUser->moneys = $newMoneys;
            $currentUser->save();

            Cart::destroy();
            return redirect()
                ->route('member.cart.index')->with('game', $game)
                ->with('success', 'Your purchase went well ! You will receive your Invoice and the activation code for your Game !');
        }else
        {
            return redirect()->route('member.cart.index')->with('error', 'Insufficient money !');
        }
    }
}

app/Http/Controllers/Member/ProfileController.php
<?php

namespace App\Http\Controllers\Member;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class ProfileController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(User $user)
    {
        $user = auth()->user();

        return view('member.profile.index')
            ->with('user', $user);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('member.profile.edit')
            ->with(['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user = auth()->user();

        $name = $request->input('name');
        $email = $request->input('email');

        $user = User::find($user->id);
        $user->name = $name;
        $user->email = $email;

        if($user->save())
        {
            $request->session()->flash('success', $user->name . ' has been modified successfully !');
        }else
        {
            $request->session()->flash('error', 'The User has not been modified !');
        }

        return redirect()->route('member.profile.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function addMoney(User $user)
    {
        return view('member.profile.addMoney')
            ->with(['user' => $user]);
    }

    public function updateMoney(Request $request, User $user)
    {
        $user = auth()->user();

        $moneys = $request->input('moneys');

        $user = User::find($user->id);
        $user->moneys += $moneys;

        if($user->save())
        {
            $request->session()->flash('success', 'Your Moneys has been added successfully !');
        }else
        {
            $request->session()->flash('error', 'Your Moneys has not been added !');
        }

        return redirect()->route('member.profile.index');
    }
}

resources/views/member/cart/index.blade.php
@extends('layouts.app')

@section('content')
@if (Cart::count() > 0 )
    <div class="px-4 px-lg-0">
        <div class="pb-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 p-5 bg-white rounded shadow-sm mb-5">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="p-2 px-3 text-uppercase">Games on Cart</div>
                                        </th>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="py-2 text-uppercase">Price</div>
                                        </th>
                                        <th scope="col" class="border-0 bg-light">
                                            <div class="py-2 text-uppercase">Delete</div>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (Cart::content() as $game)
                                        <tr>
                                            <th scope="row" class="border-0">
                                                <div class="p-2">
                                                    <img src="{{ asset('storage/gameScreen/' . $game->model->gameScreen) }}" alt="" width="70" class="img-fluid rounded shadow-sm">
                                                    <div class="ml-3 d-inline-block align-middle">
                                                        <h5 class="mb-0">{{ $game->model->name}}</h5>
                                                    </div>
                                                </div>
                                            </th>
                                            <td class="border-0 align-middle"><strong>{{ $game->model->price }} €</strong></td>
                                            <td class="border-0 align-middle">
                                                <form action="{{ route('member.cart.destroy', $game->rowId) }}" method="POST" style="margin-left: 10px;">
                                                    @csrf
                                                    @method("DELETE")
                                                    <button type="submit" class="btn"><i class="fa fa-trash"></i></button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="row py-5 p-4 bg-white rounded shadow-sm">
                    <div class="col-lg-6">
                        <div class="bg-light rounded-pill px-4 py-3 text-uppercase font-weight-bold">Order List</div>

                        <div class="p-4">
                            <ul class="list-unstyled mb-4">
                                <li class="d-flex justify-content-between py-3 border-bottom"><strong class="text-muted">Total</strong>
                                    <h5 class="font-weight-bold">{{ Cart::subtotal() }} €</h5>
                                </li>
                            </ul>
                            <a href="{{ route('member.cart.pdf') }}"><button type="button" class="btn btn-dark rounded-pill py-2 btn-block">Buy</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@else
    <div class="container-fluid" style="margin: 100px auto;">
        <div class="row">
            <div class="col-md-12">
                <div class="card-body cart">
                    <div class="col-sm-12 empty-cart-cls text-center"> <img src="" class="img-fluid mb-4 mr-3">
                        <h3><strong>Nothing in your Cart</strong></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endif
@endsection

resources/views/member/cart/receipt.blade.php
<!DOCTYPE html>
<html lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Facture</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>
    <div class="invoice-box">
        <table cellpadding="0" cellspacing="0">
            <tr class="information">
                <td colspan="3">
                    <h5><strong>EgameCenter</strong></h5>
                </td>
            </tr>
            <tr class="heading">
                <td>Game</td>
                <td>Game Code</td>
                <td>Price</td>
            </tr>
            @foreach (Cart::content() as $game)
                <tr class="item">
                    <td>{{ $game->model->name}}</td>
                    <td>{{ $game->model->code }}</td>
                    <td>{{ $game->model->price }} €</td>
                </tr>
            @endforeach
            <tr class="total">
                <td><strong>Total: {{ Cart::subtotal() }} €</strong></td>
            </tr>
        </table>
    </div>
</body>
</html>