routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
    Route::resource('/dashboard', 'DashboardController');
    Route::resource('/games', 'GamesController');
});

Route::namespace('Member')->prefix('member')->name('member.')->group(function(){
    Route::resource('/profile', 'ProfileController');
    Route::resource('/cart', 'CartController');
    Route::resource('/games', 'GameController');
    Route::resource('/notice', 'NoticeController');

    Route::get('cart/pdf-generate', 'PdfController@generatePDF')->name('cart.pdf');
    Route::get('cart/receipt', 'CartController@receipt')->name('cart.receipt');
    Route::get('profile/addMoney', 'ProfileController@addMoney')->name('profile.addMoney');

    Route::post('profile/updateMoney', 'ProfileController@updateMoney')->name('profile.updateMoney');
});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <script src="{{ asset('js/app.js') }}" defer></script>

    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/home') }}">
                    EgameCenter
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if(Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                            @else
                                <a href="/home" class="nav-link">
                                    Home
                                </a>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    <i class="fas fa-user"></i>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('member.profile.index') }}" class="nav-link">
                                        {{ Auth::user()->name }}
                                    </a>
                                    @can('manage-users')
                                        <a class="dropdown-item" href="{{ route('admin.users.index') }}">
                                            User Management
                                        </a>
                                        <a class="dropdown-item" href="{{ route('admin.dashboard.index') }}">
                                            Dashboard
                                        </a>
                                        <a class="dropdown-item" href="{{ route('admin.games.index') }}">
                                            Check Games
                                        </a>
                                    @endcan
                                    <a style="color: red;" class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            <a href="{{ route('member.profile.index') }}" class="nav-link">
                                {{ auth()->user()->moneys }} €<i class="fas fa-euro-sign"></i>
                            </a>
                            <a href="{{ route('member.cart.index') }}" class="nav-link">
                                {{--<i class="fas fa-shopping-cart"></i> <span class="badge badge-pill badge-dark">{{ Cart::count() }}</span>--}}
                            </a>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        @yield('content2')
        <main class="py-4">
            <div class="container-fluid">
                @include('partials.alerts')
                @yield('content')
            </div>
        </main>
    </div>
</body>
</html>