routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('can:manage-users')->group(function(){
    Route::resource('/users', 'UsersController', ['except' => ['show', 'create', 'store']]);
    Route::resource('/dashboard', 'DashboardController');
    Route::resource('/games', 'GamesController');
});

Route::namespace('Member')->prefix('member')->name('member.')->group(function(){
    Route::resource('/profile', 'ProfileController');
    Route::resource('/cart', 'CartController');
    Route::resource('/games', 'GameController');
    Route::resource('/notice', 'NoticeController');

    Route::get('cart/pdf-generate', 'PdfController@generatePDF')->name('cart.pdf');
    Route::get('cart/receipt', 'CartController@receipt')->name('cart.receipt');
    Route::get('profile/addMoney', 'ProfileController@addMoney')->name('profile.addMoney');

    Route::post('profile/updateMoney', 'ProfileController@updateMoney')->name('profile.updateMoney');
});

app/Game.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    public function notices()
    {
        return $this->hasMany(Notice::class, 'id_game');
    }
}

app/Http/Controllers/Admin/GamesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Game;
use App\Notice;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Facade\Ignition\Exceptions\ViewException;

class GamesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->input('search') ?? '';

        if($search != '')
        {
            $games = Game::where('name', 'like', '%' . $search . '%')
                ->get();
        }else
        {
            $games = Game::all();
        }

        return view('admin.games.index')
            ->with('games', $games);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.games.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->hasFile('gameScreen'))
        {
            $fileNameWithExt = $request->file('gameScreen')->getClientOriginalName();
        }

        if($request->hasFile('gameScreen'))
        {
            $fileNameWithExt = $request->file('gameScreen')->getClientOriginalName();
            $fileName = pathinfo($fileNameWithExt, PATHINFO_FILENAME);
            $extension = $request->file('gameScreen')->getClientOriginalExtension();
            $fileNameToStore = $fileName.'.'.$extension;
            $path = $request->file('gameScreen')->storeAs('public/gameScreen', $fileNameToStore);
        }else
        {
            $fileNameToStore = 'noscreen.jpg';
        }

        $name = $request->input('name');
        $description = $request->input('description');
        $price = $request->input('price');
        $platform = $request->input('platform');
        $quantity = $request->input('quantity');
        $code = $request->input('code');

        $game = new Game();
        $game->name = $name;
        $game->description = $description;
        $game->price = $price;
        $game->platform = $platform;
        $game->quantity = $quantity;
        $game->code = $code;
        $game->gameScreen = $fileNameToStore;
        $game->save();

        return redirect()->route('admin.games.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Game $game, Notice $notice)
    {
        return view('admin.games.show', ['game' => $game, 'notice' => $notice]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Game $game)
    {
        return view('admin.games.edit')
            ->with('game', $game);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Game $game)
    {
        if($request->hasFile('gameScreen'))
        {
            $fileNameWithExt = $request->file('gameScreen')->getClientOriginalName();
            $fileName = pathinfo($fileNameWithExt, PATHINFO_FILENAME);
            $extension = $request->file('gameScreen')->getClientOriginalExtension();
            $fileNameToStore = $fileName.'.'.$extension;
            $path = $request->file('gameScreen')->storeAs('public/gameScreen', $fileNameToStore);
        }else
        {
            $fileNameToStore = 'noscreen.jpg';
        }

        $name = $request->input('name');
        $description = $request->input('description');
        $price = $request->input('price');
        $platform = $request->input('platform');
        $quantity = $request->input('quantity');
        $code = $request->input('code');

        $game = Game::find($game->id);
        $game->name = $name;
        $game->description = $description;
        $game->price = $price;
        $game->platform = $platform;
        $game->quantity = $quantity;
        $game->code = $code;
        $game->gameScreen = $fileNameToStore;

        if($game->save())
        {
            $request->session()->flash('success', $game->name . ' has been modified successfully !');
        }else
        {
            $request->session()->flash('error', 'Error ! The Game has not been modified !');
        }

        return redirect()->route('admin.games.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Game $game)
    {
        $game->delete();

        if($game->delete())
        {
            $request->session()->flash('error', 'Error ! The Game has not been deleted !');
        }else
        {
            $request->session()->flash('success', $game->name . ' has been deleted !');
        }

        return redirect()->route('admin.games.index');
    }
}

app/Http/Controllers/Member/GameController.php
<?php

namespace App\Http\Controllers\Member;

use App\Http\Controllers\Controller;
use App\Game;
use Illuminate\Http\Request;

class UserGameController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Game $game)
    {
        return view('member.games.show')
            ->with(['game' => $game]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/games/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form action="{{ route('admin.games.store') }}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="mb-3">
            <label for="name" class="form-label">Name Game</label>
            <input type="text" name="name" class="form-control">
        </div>

        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <input type="text" name="description" class="form-control">
        </div>

        <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="number" name="price" class="form-control">
        </div>

        <div class="mb-3">
            <label for="platform" class="form-label">Platform</label>
            <select class="form-select" name="platform">
                <option selected>Platform</option>
                <option value="PC">PC</option>
                <option value="XBOXONE">XBOX</option>
                <option value="XBOXX">XBOX Series X</option>
                <option value="PS4">PS4</option>
                <option value="PS5">PS5</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="quantity" class="form-label">Quantity</label>
            <input type="number" name="quantity" class="form-control">
        </div>

        <div class="mb-3">
            <label for="code" class="form-label">Game Code</label>
            <input type="text" name="code" class="form-control">
        </div>

        <div class="mb-3">
            <label for="gameScreen" class="form-label">Image of Game</label>
            <input type="file" name="gameScreen" class="form-control" id="gameScreen">
        </div>

        <button type="submit" class="btn btn-primary">Add Game</button>
    </form>
</div>
@endsection

resources/views/admin/games/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form action="{{ route('admin.games.update', $game) }}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="mb-3">
            <label for="name" class="form-label">Name Game</label>
            <input type="text" name="name" class="form-control" value="{{ $game->name }}">
        </div>

        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <input type="text" name="description" class="form-control" value="{{ $game->description }}" >
        </div>

        <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="number" name="price" class="form-control" value="{{ $game->price }}">
        </div>

        <div class="mb-3">
            <label for="platform" class="form-label">Platform</label>
            <select class="form-select" name="platform">
                <option selected>{{ $game->platform }}</option>
                <option value="PC">PC</option>
                <option value="XBOXONE">XBOX</option>
                <option value="XBOXX">XBOX Series X</option>
                <option value="PS4">PS4</option>
                <option value="PS5">PS5</option>
            </select>
        </div>

        <div class="mb-3">
            <label for="quantity" class="form-label">Quantity</label>
            <input type="number" name="quantity" class="form-control" value="{{ $game->quantity }}">
        </div>

        <div class="mb-3">
            <label for="code" class="form-label">Game Code</label>
            <input type="text" name="code" class="form-control" value="{{ $game->code }}">
        </div>

        <div class="mb-3">
            <label for="gameScreen" class="form-label">Image of Game</label>
            <input type="file" name="gameScreen" class="form-control" id="gameScreen">
        </div>

        <button type="submit" class="btn btn-primary">Edit Game</button>
    </form>
</div>
@endsection

resources/views/admin/games/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="card">
            <div class="card-header">All Games</div>
            
            <div class="card-body">
                <a href="{{ route('admin.games.create') }}"><button type="button" class="btn btn-dark">Add Game</button></a>
                <div class="row row-cols-1 row-cols-md-3 g-4">
                    @foreach($games as $game)
                    <div class="col" style="margin-top: 35px;">
                        <div class="card" style="width: 18rem;">
                            <img style="height: 200px;" src="{{ asset('storage/gameScreen/' . $game->gameScreen) }}" class="card-img-top" alt="{{$game->gameScreen}}">
                            <div class="card-body">
                                <h5 class="card-title"><strong>Name Game :</strong> {{ $game->name }}</h5>
                                <p class="card-text"><strong>Price :</strong> {{ $game->price }} €</p>
                                <p class="card-text"><strong>Platform :</strong> {{ $game->platform }}</p>
                                <p class="card-text"><strong>Quantity :</strong> {{ $game->quantity }}</p>
                                <p class="card-text"><strong>Code :</strong> {{ $game->code }}</p>
                                <div style="display: flex;">
                                    <a href="{{ route('admin.games.edit', $game->id) }}"><button class="btn btn-primary">Edit Game</button></a>
                                    <form action="{{ route('admin.games.destroy', $game) }}" method="POST" style="margin-left: 10px;">
                                        @csrf
                                        @method("DELETE")
                                        <button type="submit" class="btn btn-danger">Delete Game</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/games/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <h1 class="my-4">EgameCenter</h1>
            <div class="list-group">
                <a href="#" class="list-group-item active">Category #1</a>
                <a href="#" class="list-group-item">Category #2</a>
                <a href="#" class="list-group-item">Category #3</a>
            </div>
        </div>

        <div class="col-lg-9">
            <div class="card mt-4">
                <img style="height: 400px;" class="card-img-top img-fluid" src="{{ asset('storage/gameScreen/' . $game->gameScreen) }}" alt="">
                <div class="card-body">
                    <h3 class="card-title">{{ $game->name }}</h3>
                    <p class="card-text">{{ $game->description }}</p>
                    <h4>{{ $game->price }} €</h4>
                    <br><br>
                    @if($game->quantity === 0)
                        <button type="button" class="btn btn-success disabled">Buy</button>
                    @else()
                        <button type="button" class="btn btn-success">Buy</button>
                    @endif
                </div>
            </div>

            <div class="card card-outline-secondary my-4">
                <div class="card-header">
                    Notices
                </div>
                <div class="card-body">
                    @foreach($game->notices as $notice)
                        <p>{{ $notice->description }}</p>
                        <h3>{{ $notice->note }}</h3>
                        <small class="text-muted">Posted by {{ $notice->auteur }} on {{ $notice->created_at }} 
                        @if($notice->auteur === auth()->user()->name)
                            <a href="{{ route('member.notice.edit',["id_game"=>$game->id, $notice ]) }}"><img src=""/>Edit Notice</a> 
                            <form action="{{ route('member.notice.destroy', $notice) }}" method="POST" style="margin-left: 10px;">
                                @csrf
                                @method("DELETE")
                                <button class="btn btn-light"><img src=""/>Delete Notice</button>  
                            </form>
                        @endif
                        </small>
                        <hr>
                    @endforeach
                <a href=" {{ route("member.notice.create", ["id_game"=>$game->id]) }} " class="btn btn-success">Add Notice</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection